name: Upload to S3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
        env:
          CI: false
      - name: zip
        run: cd build && zip -r artifacts.zip *
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
      - name: Deploy app to S3 bucket
        run: aws s3 cp build/artifacts.zip s3://${{ secrets.AWS_BUCKET }}/oracle/
      - name: Trigger lambda
        run: aws --region eu-central-1 lambda invoke --function-name ${{ secrets.AWS_LAMBDA }} outfile
