# GitHub Dhall CI
name: dhall

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dhall-lang/setup-dhall@v4
      - run: dhall version
        run: |
          dhall version
          make
        env:
          CI: true
