# contractshark workflow pipeline
#  spdx-license-identifier: ISC
#  v0.2.2
name: contractshark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: ['12.x']
        os: [ubuntu-latest, windows-latest]
        test_number:
          - 1
          - 2

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: npm install, build, and test
        run: |
          npm install -g codecov
          npm install -g ganache-cli
          yarn install

      - name: Test ${{ matrix.test_number }}
        run: make test-coverage-${{ matrix.test_number }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }
         flag-name: run-${{ matrix.test_number }}
         parallel: true

  finish:
  #   needs: test 1, test 2
     runs-on: ubuntu-latest
     steps:
     - name: Coveralls Finished
       uses: coverallsapp/github-action@master
       with:
         github-token: ${{ secrets.GITHUB_TOKEN }
         parallel-finished: true
