# GitHub Nodejs CI
name: nodejs

on: [push, pull_request]
  
env:
  CI: true
  FORCE_COLOR: 2


jobs:
  run:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: ["10.x", "12.x", "14.x"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

# Cache Optimization 

      - uses: actions/cache@v2.1.4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install, build, and test
        run: |
          yarn install
        env:
          CI: true

# Semantic Distribution  

      - uses: cycjimmy/semantic-release-action@v2
        with:
         semantic_version: 16
         branches: |    
           [
            '+([0-9])?(.{+([0-9]),x}).x',
            'master', 
            'next', 
            'next-major', 
            {
              name: 'beta', 
              prerelease: true
            }, 
            {
              name: 'alpha', 
              prerelease: true
            }
           ]
         extra_plugins: |
          @semantic-release/changelog@3.0.0
          @semantic-release/git
