name: CI

on:
  pull_request:
    branches:
    - master
    types: [opened, synchronize, closed]

defaults:
  run:
    shell: bash
      
env:
  CI: true
  FORCE_COLOR: 2

        
jobs:
  pipeline:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
   
    strategy:
      fail-fast: false
      matrix:
        node: ['14.x']
        os: ['ubuntu-latest']
        
    steps:
    - name: debug
      if: contains(github.event.pull_request.labels.*.name, 'debug')
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        env
        echo "$GITHUB_CONTEXT"
    - uses: smartlyio/check-versioning-action@v5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '12.13.1'
    - name: yarn install
      run: yarn install --frozen-lockfile --link-duplicates --silent;
    - name: test
      run: yarn run test
    - name: coverage
      run: yarn run cover
    - name: typecheck
      run: yarn run typecheck
